### ISSUE TITLE
demo for 3 physical nomad master and 3 nomad worker node

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad-autoscaler-demos#32]
Hello Team,
I would like to know if we have in premises datacenter and we have vcentre cluster where we have 3 nomad master and 3 worker nodes. the vagrant example works perfect but this is applicable only for a single node cluster where we can define easily. But let just say we have a cluster of the above situation the example does not work due to static configs.
So let me know how we can tackle that.

**Comment by gc-ss** [comment]
> But let just say we have a cluster of the above situation

The demo will still work in that scenario but I believe you will now have to activate the enterprise license into the Nomad Autoscaler Enterprise so it works on the cluster.

I'm unsure if the team that monitors these tickets can get you that information or whether you will need to contact sales.

**Comment by thatsk** [comment]
I don't think so  all things are in demo are saying all are oss edition and only dynamic scaling is enterprise one

**Comment by gc-ss** [comment]
It's unclear to me what you're trying to do. Are you not interested in running all the 3 demos in this repo?

There are 3 demos in this repo:
- Horizontal Application Scaling
- Horizontal Cluster Scaling
- Dynamic Application Sizing

So yes, you do need an enterprise license to run all the 3 demos in this repo.

If you want to run a subset, you have to mention which otherwise there is no way for anyone reading this issue to know which ones are of interest to you.

**Comment by thatsk** [comment]
Horizontal application scaling.

**Comment by thatsk** [comment]
in haproxy.nomad 
```
    network {
      port "webapp" {
        static = 8000
      }

      port "prometheus_ui" {
        static = 9090
      }

      port "grafana_ui" {
        static = 3000
      }

      port "haproxy_ui" {
        static = 1936
      }

      port "haproxy_exporter" {}
    }
```

**Comment by thatsk** [comment]
its static configuration so that let just say you have 3 nomad agents and it is distributing on all node then this scenario not work

**Comment by thatsk** [comment]
i'm interested in community edition which works on single node. But let just say you cluster of 3 worker nodes and 3 master nodes then vagrant demo will not work for horizontal application scaling.

**Comment by thatsk** [comment]
@jrasell  Thanks for the information. But from this idea can we just use dynamic configuration for a single vagrant node. as of now, we are using the static port. and how do we handle when it comes to dynamic port allocation for all service and proxy will look for that configuration. we look forward for your suggestions.

**Comment by thatsk** [comment]
also just wanted to know do we if it's an above situation and do we want to deploy nomad autoscaler on all nomad worker node and Loki instance.

**Comment by lgfa29** [comment]
Hi @thatsk 👋 

The `haproxy.nomad` job is the public traffic ingress gateway for the cluster, so it must have static port allocation, otherwise it would be impossible to know which port to connect to from the outside.

One thing that we are missing is defining its type as a `system` job. This means that there will be one allocation (and only one) for this job in every client. This is normally what you would do in an environment with multiple clients. 

Checkout our [Traefik](https://github.com/hashicorp/nomad-autoscaler-demos/blob/main/cloud/demos/on-demand-batch/shared/terraform/modules/nomad-jobs/jobs/traefik.nomad) job from another demo as an example. Traefik serves a similar purpose as HAProxy in the horizontal application scaling.

> also just wanted to know if it's an above situation and do we want to deploy nomad autoscaler job to be on all nomad worker node and also promtail should be deployed on all nomad worker node or not

No, you should have just one Autoscaler allocation running. In the demo, Promtail is a sidecar, so it will always run alongside the Autoscaler. Promtail is also only used to register Loki annotations in the Grafana dashboard (those vertical blue lines). You don't need it if you are looking to have this functionality.

**Comment by thatsk** [comment]
First of all thanks for replying @lgfa29  and explaining it very well to clear my confusion. For large nomad cluster, we just require only one autosclaer to deployed on any nomad worker node. but let just say if we define haproxy as system job its going to act like daemon job which can run every nomad worker node why we would we require that if we already deployed only one service on node. if any information would you like to share that would be very great.

**Comment by thatsk** [comment]
also, do we have the same example explained with traefik
that would be great  if we can try it out with traefik instead of haproxy

**Comment by thatsk** [comment]
is there a way can we scale the application using web cpu and memory usage APM?
i tried to go through this page.
```check {
  source = "nomad-apm"
  query  = "avg_cpu"
  ...
}```

**Comment by jrasell** [comment]
Hi @thatsk, the HashiCorp Learn site has a [Traefik Load Balancing](https://learn.hashicorp.com/tutorials/nomad/load-balancing-traefik?in=nomad/load-balancing) guide that runs through an example ingress using Traefik.

What question do you have regarding the `nomad-apm`? You can indeed use that APM to scale your application based on CPU and Memory usage.

**Comment by thatsk** [comment]
is there any example for nomad-APM to scale application based on web app cpu and memory increases?
otherwise, we can close this thread. from this discussion, I am raising two issues like a demo with traefik load balancing and Fabio load balancer which is best in these

**Comment by thatsk** [comment]
@jrasell I have added another issue regarding traefik and Fabio load balancer so that this can separate from this thread
https://github.com/hashicorp/nomad-autoscaler-demos/issues/34
https://github.com/hashicorp/nomad-autoscaler-demos/issues/33

**Comment by jrasell** [comment]
Hi @thatsk we currently have https://github.com/hashicorp/nomad-autoscaler-demos/issues/18 open to track adding a demo which utilises the Nomad APM. I'll bring this up internally so we can discuss the priority.

I am going to go ahead and close this issue. Please feel free to use the Nomad discuss forum linked above to raise any followup questions.
