### ISSUE TITLE
Vagrant Horizontal Application scaling demo with Fabio Load balancer

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad-autoscaler-demos#34]

**Comment by jrasell** [comment]
Hi @thatsk and thanks for this request. There is some internal discussion on improving the Nomad demo environments overall. That being said we do not currently wish to duplicate demos whilst changing a single technology involved. The demos are aimed at showcasing the Nomad Autoscaler only.

In order to understand how to utilise different load balancers such as Fabio within your environment, I would suggest heading over to the [Nomad Learn Load Balancing](https://learn.hashicorp.com/collections/nomad/load-balancing) track. This forms the canonical place for learning how to integrate different load balancers into a Nomad environment.
